import { useState, useCallback } from 'react';
import { ClipboardIcon, DownloadIcon } from './ui/Icons';
import { Toast } from './ui/Toast';
import { CRAWLERS } from '../data/crawlers';

function generateOutput(blockedIds) {
  if (blockedIds.size === 0) {
    return '# No AI crawlers are currently blocked.\n# Use the toggles above to block specific crawlers.';
  }

  const lines = [
    '# AI Crawler Control — generated by DreamHost Tools',
    '# Add these rules to the top of your robots.txt file',
    '',
  ];

  const blockedCrawlers = CRAWLERS.filter((c) => blockedIds.has(c.id));
  blockedCrawlers.forEach((crawler) => {
    lines.push(`# ${crawler.operator} — ${crawler.description.split('.')[0]}`);
    lines.push(`User-agent: ${crawler.id}`);
    lines.push('Disallow: /');
    lines.push('');
  });

  return lines.join('\n').trim();
}

export function OutputPanel({ blockedIds }) {
  const [toastVisible, setToastVisible] = useState(false);
  const output = generateOutput(blockedIds);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(output).then(() => {
      setToastVisible(true);
    });
  }, [output]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots-ai.txt';
    a.click();
    URL.revokeObjectURL(url);
  }, [output]);

  const hideToast = useCallback(() => setToastVisible(false), []);

  const lineCount = output.split('\n').length;

  return (
    <div className="card-gradient border border-metal/20 rounded-2xl overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 border-b border-metal/20">
        <div className="flex items-center gap-2">
          <div className="w-2.5 h-2.5 rounded-full bg-coral" />
          <div className="w-2.5 h-2.5 rounded-full bg-tangerine" />
          <div className="w-2.5 h-2.5 rounded-full bg-turtle" />
          <span className="ml-2 text-sm text-galactic font-mono">robots.txt snippet</span>
          <span className="text-xs text-metal">— {lineCount} lines</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-galactic hover:text-white border border-metal/30 hover:border-metal/60 rounded-lg transition-colors focus:outline-none focus:ring-1 focus:ring-azure"
          >
            <ClipboardIcon className="w-4 h-4" />
            Copy
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-azure hover:bg-azure-hover text-white rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-azure focus:ring-offset-2 focus:ring-offset-abyss"
          >
            <DownloadIcon className="w-4 h-4" />
            Download
          </button>
        </div>
      </div>
      <div className="p-4 max-h-72 overflow-auto">
        <pre className="text-sm font-mono whitespace-pre leading-relaxed">
          {output.split('\n').map((line, i) => (
            <div key={i} className="flex">
              <span className="w-6 text-right pr-3 text-metal select-none flex-shrink-0 text-xs leading-5">{i + 1}</span>
              <span className={
                line.startsWith('#') ? 'text-galactic italic' :
                line.startsWith('User-agent') ? 'text-azure' :
                line.startsWith('Disallow') ? 'text-coral' :
                'text-cloudy'
              }>{line || ' '}</span>
            </div>
          ))}
        </pre>
      </div>
      <Toast message="Copied to clipboard!" isVisible={toastVisible} onHide={hideToast} />
    </div>
  );
}
