/**
 * Export redirect maps in multiple formats.
 */

export function exportCSV(rows) {
  const header = 'old_url,new_url,redirect_type';
  const lines = rows.map((r) => `${csvEscape(r.from)},${csvEscape(r.to)},${r.type}`);
  return [header, ...lines].join('\n');
}

export function exportHtaccess(rows) {
  const lines = [
    '# Redirect Map — generated by DreamHost Tools',
    '# Add these rules to your .htaccess file',
    '',
  ];
  rows.forEach((r) => {
    const from = r.from.trim();
    const to = r.to.trim();
    if (!from || !to) return;
    // .htaccess Redirect directive: needs relative path for "from"
    const fromPath = from.startsWith('http') ? tryGetPath(from) : from;
    const code = r.type === '301' ? '301' : r.type === '302' ? '302' : '307';
    lines.push(`Redirect ${code} ${fromPath} ${to}`);
  });
  return lines.join('\n');
}

export function exportNginx(rows) {
  const lines = [
    '# Redirect Map — generated by DreamHost Tools',
    '# Add these rules inside your server{} block',
    '',
  ];
  rows.forEach((r) => {
    const from = r.from.trim();
    const to = r.to.trim();
    if (!from || !to) return;
    const fromPath = from.startsWith('http') ? tryGetPath(from) : from;
    const flag = r.type === '301' ? 'permanent' : 'redirect';
    lines.push(`rewrite ^${escapeRegex(fromPath)}$ ${to} ${flag};`);
  });
  return lines.join('\n');
}

export function exportJSON(rows) {
  const data = rows
    .filter((r) => r.from.trim() && r.to.trim())
    .map((r) => ({ from: r.from.trim(), to: r.to.trim(), type: r.type }));
  return JSON.stringify(data, null, 2);
}

export function exportCloudflare(rows) {
  const data = rows
    .filter((r) => r.from.trim() && r.to.trim())
    .map((r) => ({
      source: r.from.trim(),
      destination: r.to.trim(),
      permanent: r.type === '301',
    }));
  return JSON.stringify(data, null, 2);
}

function csvEscape(val) {
  if (!val) return '';
  if (val.includes(',') || val.includes('"') || val.includes('\n')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function tryGetPath(url) {
  try {
    return new URL(url).pathname;
  } catch {
    return url;
  }
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
